[package]
name = "web"
version = "0.0.1"
edition = "2021"

[dependencies]
macros = { path = "../macros" }
reqwest = { version = "0.12.4", features = ["json" ] }
serde = { version =  "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }

